helptext
a2-4am/4cade pull request #643
Opened 2024-10-16 14:45 UTC by badvision

2024-10-16 22:19 UTC, badvision commented
Ok after some cleanup and corrections I'm pretty much set with my change set now.  Make sure to squash/merge this since the commit history is not likely very useful or interesting to anyone.

2024-10-17 13:11 UTC, badvision commented
I've reduced the content to fit the double space requirement, trying to sacrifice as little meaning as possible.  Let me know if this works.

2024-10-18 20:34 UTC, a2-4am requested changes

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/ALIENS
> +   Return * * * * * * * * *Next Level
These need to span the entire width (40 columns)

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/AQUATRON
> +f / B0 * * * * * machine guns (unlimited)
capital F, capital D, capital E in Esc

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/BLITZKRIEG
> +     "SHOOT EM DOWN WITH YOUR GUN."
no all-caps

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/BLITZKRIEG
> +u or joystick right* * * * * * * * aim up
capital U, capital D, capital F

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/BUBBLE.HEAD
> +  space / B0 * * * * * * * Force Field
expand to full 40-columns

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/BUBBLE.HEAD
> +  ctrl-r * * * * * * * * Restart Level
`Ctrl-R`

`restart level`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/BUBBLE.HEAD
> +  esc* * * *Pause    ctrl-s* * * Sound
`Esc`

`Ctrl-S`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/CALI.RAISINS
> +CTRL+J* *Joystick   ESC * * *Next Level
`Ctrl-J`

`Esc`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/CR
> +ctrl-c* * *config   ctrl-r* * * *restart
`Ctrl-C`

`Ctrl-R`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/CR
> +z * * * * suicide   R * * *reincarnation
`Z`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/DIAMOND.MINE
> +ctrl-b * * * * restart with new options
`Ctrl-B` and similar capitalization

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/DRAGONFIRE
> +0-9 * * difficulty  esc * * * * * pause
capitalization changes like others

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/G.I.JOE
> +Button 1 or ctrl + direction* * * * *aim
`Ctrl`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/GAUNTLET
> +      ctrl-p * * * * * * * * pause
capitalization and width

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/MS
> + ESC * * * * * * * * * * * * * * *Pause
`Esc`

`pause`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/MS
> + Space or Button 0 * * * * * * * * Jump
`jump`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/SERPENTINE
> +c* * * * * * * * * * change key mappings
`C`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/SERPENTINE
> +return * * * * * * view high score table
`Return`

2024-10-18 20:34 UTC, a2-4am commented on res/GAMEHELP/SERPENTINE
> +esc* * * * * * * * * * * * * * * * pause
`Esc`

2024-10-19 02:38 UTC, badvision commented
Thanks for your exceeding patience!  Let me know if these changes work for you.

2024-10-19 14:48 UTC, merged

2024-10-19 14:51 UTC, a2-4am commented
Thank you!